AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  Enabled: false

LineLength:
  Description: 'Limit lines to 120 characters.'
  Enabled: true
  Max: 120

SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
